language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_26e8a1e5641f_key -iv $encrypted_26e8a1e5641f_iv -in key.json.enc -out key.json -d
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - gcloud auth activate-service-account --key-file key.json
  - gcloud container clusters get-credentials soa-service --zone asia-southeast1-b --project soa-group-7-174

script:
  - docker build -t asia.gcr.io/soa-group-7-174/report:$TRAVIS_JOB_NUMBER .
  - gcloud docker -- push asia.gcr.io/soa-group-7-174/report:$TRAVIS_JOB_NUMBER
  - kubectl set image deployment/report report=asia.gcr.io/soa-group-7-174/report:$TRAVIS_JOB_NUMBER

services:
  - docker